Create reduce-javascript-es.md
breatheco-de/content pull request #1510
Opened 2023-05-23 17:52 UTC by DF27ARTS

2023-05-25 15:34 UTC, tommygonzaleza requested changes

2023-05-25 15:34 UTC, tommygonzaleza commented on src/content/how-to/reduce-javascript-es.md
> +El método `reduce()` de Javascript recibe dos parámetros:
Para explicar los parametros que recibe y como funciona, puedes basarte un poco en como se hizo en este [articulo](https://github.com/breatheco-de/content/blob/3dd68d56793fa3834032c51c3673cfdf92d4549b/src/content/lesson/metodo-foreach-javascript.md?plain=1#L17)

2023-05-25 15:34 UTC, tommygonzaleza commented on src/content/how-to/reduce-javascript-es.md
> +> que si no lo colocas el parámetro **acumulador** toma como valor inicial el primer valor del array y si le pasas un array vacío
Aqui hay un error de redaccion, creo que la segunda nota no va

2023-05-25 15:34 UTC, tommygonzaleza commented on src/content/how-to/reduce-javascript-es.md
> +    { id:  1, ciudad:  "New york", temperatura:  "25 grados" },
Cambia ciudad por nombre para que no se confunda luego con el parametro

2023-05-25 15:34 UTC, tommygonzaleza commented on src/content/how-to/reduce-javascript-es.md
> +const temperaturaPromedio = ciudades.reduce((acumulador, ciudad, indice) => {
Lo ideal en este ejemplo es que con reduce se haga la suma de todos los numeros y luego en una linea a parte despues del reduce, se divide entre la cantidad de elementos para obtener el promedio. Se debe quitar el if de adentro de la funcion del reduce

2023-05-25 21:07 UTC, DF27ARTS commented
Hice los cambios en la esplicación y en el ejemplo de de ciudades.

2023-05-29 15:11 UTC, tommygonzaleza commented on src/content/how-to/reduce-javascript-es.md
> +El método `reduce()` de Javascript recibe dos parámetros:
SIgue sin parecerse, mira como se estan comentando los parametros

2023-05-29 18:38 UTC, DF27ARTS commented on src/content/how-to/reduce-javascript-es.md
> +El método `reduce()` de Javascript recibe dos parámetros:
Hice modificación basas mas en el ejemplo del articulo que me pasaste como refecencia. Porfavor dice si te parece que debo hacer mas camcios.

2023-05-31 01:19 UTC, merged