Create pandas-data-cleaning.md
breatheco-de/content pull request #1603
Opened 2023-06-21 22:33 UTC by DF27ARTS

2023-06-21 22:35 UTC, DF27ARTS commented
Por favor dime que te parece el articulo, si es muy lago, si la explicaciones estan bien y el codigo.

2023-06-26 16:58 UTC, tommygonzaleza requested changes

2023-06-26 16:58 UTC, tommygonzaleza commented on src/content/how-to/pandas-data-cleaning.md
> +### 4. Set a unique pattern for a column
Revisa este ejemplo de codigo, no creo que funcione, si borras los datos del data frame y luego intentas acceder a ellos, ya deberian estar borrados

2023-06-26 18:03 UTC, DF27ARTS commented on src/content/how-to/pandas-data-cleaning.md
> +### 4. Set a unique pattern for a column
Okay dale, lo voy a revisar

2023-06-26 18:10 UTC, tommygonzaleza commented on src/content/how-to/pandas-data-cleaning.md
> +### 4. Set a unique pattern for a column
Gracias, quedo pendiente

2023-06-26 19:54 UTC, merged