Update pandas-tutorial.es.md
breatheco-de/content pull request #1639
Opened 2023-06-30 12:51 UTC by valerybriz

Resolve #1535

2023-07-10 17:43 UTC, tommygonzaleza requested changes

2023-07-10 17:43 UTC, tommygonzaleza commented on src/content/lesson/pandas-tutorial.es.md
> +Explicación del ejemplo
Falto la explicacion del ejemplo

2023-07-10 17:43 UTC, tommygonzaleza commented on src/content/lesson/pandas-tutorial.es.md
> +
Falta agregar una introduccion al ejemplo, seria bueno que indiqueas de que trata el ejemplo en la introduccion para que el lector sepa lo que va a leer, sino va a quedar un poco perdido sobre que trata ese codigo

2023-07-10 17:43 UTC, tommygonzaleza commented on src/content/lesson/pandas-tutorial.es.md
> +```python
Separa cada metodo del df en sub puntos diferentes y agregar la explicacion antes del ejemplo de codigo. Cada metodo debe tener su subtitulo, explicacion y bloque de codigo propio

2023-07-10 17:43 UTC, tommygonzaleza commented on src/content/lesson/pandas-tutorial.es.md
> +import pandas as pd
Siguiendo los pasos si en este punto corro `import pandas as pd` me da error
<img width="1469" alt="Screenshot 2023-07-10 at 1 39 36 PM" src="https://github.com/breatheco-de/content/assets/56565994/fe60d7c0-b50f-49a0-b0e7-5383b40347e1">

2023-07-10 17:43 UTC, tommygonzaleza commented on src/content/lesson/pandas-tutorial.es.md
> +Al aplicar el método value_counts() podremos obtener el conteo de los valores de una columna, agrupados por sus distintos valores. En este caso nos gustaría saber cuales son las alcaldías que tienen
poner como codigo `value_counts()`

2023-07-11 07:13 UTC, valerybriz commented on src/content/lesson/pandas-tutorial.es.md
> +import pandas as pd
si que funciona con esos 2 simples pasos entonces puede que te haya faltado hacer el pip install dentro del entorno virtual que explico en el tutorial y que entonces al hacer el import esté intentando obtener las librerías de un entorno diferente

2023-07-11 07:14 UTC, valerybriz commented on src/content/lesson/pandas-tutorial.es.md
> +import pandas as pd
la solución es que sigas el orden de los pasos, activar el entorno virtual, luego hacer el pip install y finalmente hacer el import

2023-09-08 08:09 UTC, valerybriz commented on src/content/lesson/pandas-tutorial.es.md
> +
👍

2023-09-08 08:10 UTC, valerybriz commented on src/content/lesson/pandas-tutorial.es.md
> +Explicación del ejemplo
👍

2023-09-08 08:16 UTC, valerybriz commented on src/content/lesson/pandas-tutorial.es.md
> +```python
👍

2023-09-08 08:17 UTC, valerybriz commented on src/content/lesson/pandas-tutorial.es.md
> +Al aplicar el método value_counts() podremos obtener el conteo de los valores de una columna, agrupados por sus distintos valores. En este caso nos gustaría saber cuales son las alcaldías que tienen
👍

2024-05-09 16:10 UTC, closed without merging