Create react-global-context.md
breatheco-de/content pull request #1657
Opened 2023-07-14 02:29 UTC by DF27ARTS

Este articulo es un poco mas grande de lo abitual, por favor dime si cres que es muy grande y devería cambiarlo o si cres que esta bien asi como esta.

2023-07-20 15:47 UTC, tommygonzaleza requested changes

2023-07-20 15:47 UTC, tommygonzaleza commented on src/content/how-to/react-global-context.md
> +First, create the global context, to create the global context use the `createContext()`  method of React and pass it as a parameter an initial value.
Agrega un ejemplo de que podria ser ese valor inicial

2023-07-20 15:48 UTC, tommygonzaleza commented
Por otro lado el ejemplo es muy largo, aplica un ejemplo sobre el dark mode, en el que tengas un navbar donde se puede cambiar y unos cards que reciben el global context del theme y cambian de color segun el theme de la pagina

2023-07-21 14:26 UTC, DF27ARTS commented on src/content/how-to/react-global-context.md
> +First, create the global context, to create the global context use the `createContext()`  method of React and pass it as a parameter an initial value.
Mejore la esplicación y aclare que el valor inicial puede ser de qualquier tipo de dato.

2023-07-21 14:29 UTC, DF27ARTS commented
Agrege un nuevo ejemplo de productos falsos, el projectos tiene tres componentes.  App.jsx donde se crea el contexto global, Navbar.jsx que tienen el boton para actualizar el tema de la aplicación y Cards.jsx que tiene tres cards con productos falsos para simular una applicación.

2023-07-24 20:25 UTC, tommygonzaleza approved these changes

2023-07-24 20:25 UTC, merged