Create que-son-las-librerias-de-terceros.md
breatheco-de/content pull request #1723
Opened 2023-08-08 17:57 UTC by DF27ARTS

2023-08-15 00:00 UTC, tommygonzaleza requested changes

2023-08-15 00:00 UTC, tommygonzaleza commented on src/content/how-to/que-son-las-librerias-de-terceros.md
> +import tensorflow as tf
Cambia el ejemplo de tensorflow por una libraria sencilla de utilizar. Recuerda que este articulo es para principiantes que no saben nada del mundo de programacion. Agrega una libreria muy util y sencilla, y la pones de primera entre los ejemplos

2023-08-15 20:11 UTC, DF27ARTS commented on src/content/how-to/que-son-las-librerias-de-terceros.md
> +import tensorflow as tf
Cambié el ejemplo de TensorFlow por un ejemplo de la librería Requests.

2023-08-21 16:59 UTC, tommygonzaleza approved these changes

2023-08-21 16:59 UTC, tommygonzaleza approved these changes

2023-08-21 16:59 UTC, merged