consistency
breatheco-de/content pull request #204
Opened 2020-10-08 19:43 UTC by ElviraQDP

2020-10-13 14:05 UTC, alesanchezr commented on src/content/lesson/what-is-react-flux.es.md
> +(Siempre es un evento típico de JS como: hacer clic, on hiver, cambiar el tamaño, etc.)
`hover` en vez de `hiver`

2020-10-13 14:06 UTC, alesanchezr commented on src/content/lesson/what-is-react-flux.es.md
> +***Todo comienza cuando el usuario debe hacer clic en el icono de la papelera. Es por eso que necesitamos iniciar nuestra aplicación escuchando el típico evento onClic en el botón de eliminar.***
`onClick` instead of `onClic` because its a reserved word.

2020-10-23 17:31 UTC, marcogonzalo requested changes

2020-10-23 17:31 UTC, marcogonzalo commented on src/content/lesson/what-is-react-flux.es.md
> +subtitle: "Sin Flux, React es solo una linda librería de front-end. React Flux lo convertirá en un marco - que le dará a tu aplicación una estructura definida - cuidando la capa de procesamiento de d
Sugerencia: "marco de trabajo" en lugar de "marco". Es la correcta traducción de "framework"
Sugerencia: donde dice ", y mucho más lo que es el flujo" reemplazar por "y, aún más, el flujo"

2020-10-23 17:31 UTC, marcogonzalo commented on src/content/lesson/what-is-react-flux.es.md
> +Vistas/Views (Components)     |Cada componente React que llama a cualquier acción Flux es llamada una vista.  La razón para llamar a esos componentes de una manera diferente es porque se supone que l
Sugerencia: En lugar de "Una vez que un componente React esté codificado de forma rígida a Flux", creo que quedaría mejor: "Una vez que un componente React esté vinculado de forma rígida a Flux"

2020-10-26 17:50 UTC, marcogonzalo requested changes

2020-10-26 17:50 UTC, marcogonzalo commented on src/content/lesson/what-is-react-flux.es.md
> +subtitle: "Sin Flux, React es solo una linda biblioteca de front-end. React Flux lo convertirá en un marco - que le dará a tu aplicación una estructura definida - ocupándose de la capa de procesamien
Faltó una coma después de "aún más, " :-$ sorry :-P

2020-10-26 17:50 UTC, marcogonzalo commented on src/content/lesson/what-is-react-flux.es.md
> +subtitle: "Sin Flux, React es solo una linda biblioteca de front-end. React Flux lo convertirá en un marco - que le dará a tu aplicación una estructura definida - ocupándose de la capa de procesamien
amo que uses biblioteca en lugar de librería jajajaja

2020-10-26 17:50 UTC, marcogonzalo commented on src/content/lesson/what-is-react-flux.es.md
> +subtitle: "Sin Flux, React es solo una linda librería de front-end. React Flux lo convertirá en un marco de trabajo - que le dará a tu aplicación una estructura definida - cuidando la capa de procesa
"y, aún más, el flujo." 

Para que quede como el de abajo

2020-10-27 00:01 UTC, ElviraQDP commented on src/content/lesson/what-is-react-flux.es.md
> +subtitle: "Sin Flux, React es solo una linda biblioteca de front-end. React Flux lo convertirá en un marco - que le dará a tu aplicación una estructura definida - ocupándose de la capa de procesamien
ajaaaajaajaajaja, se me fue cambiarla!! a ti te parece la palabra biblioteca???

2020-12-11 21:29 UTC, alesanchezr approved these changes

2020-12-11 21:29 UTC, merged