Refactor de articulo de flux
breatheco-de/content pull request #2129
Opened 2024-02-05 19:27 UTC by arnaldoperez

2024-02-11 07:19 UTC, GhostGirl03 requested changes
comment; i am just proving this stuff

2024-02-12 17:19 UTC, alesanchezr requested changes

2024-02-12 17:19 UTC, alesanchezr commented on src/content/lesson/context-api.es.md
migrar links a playcode

2024-02-12 17:19 UTC, alesanchezr commented on src/content/lesson/context-api.md
> +<iframe src="https://replit.com/@4GeeksAcademy/Demo-Context-API?embed=true&run=true#src/index.jsx" style="width:100%; height:500px; border:0; border-radius: 4px;" ></iframe>
migrsar a playcode

2024-02-12 17:19 UTC, alesanchezr commented on src/content/lesson/what-is-react-flux.es.md
regresar a version original y poner warning de legacy y agregar un link para la nueva manera de manejar los datos de una aplicacion

2024-02-12 17:19 UTC, alesanchezr commented on src/content/lesson/what-is-react-flux.md
regresar a version original y poner warning de legacy y agregar un link para la nueva manera de manejar los datos de una aplicacion

2024-02-16 17:01 UTC, alesanchezr approved these changes

2024-02-16 17:01 UTC, merged