consistency, change of status
breatheco-de/content pull request #222
Opened 2020-10-12 22:56 UTC by ElviraQDP

2020-10-13 14:03 UTC, alesanchezr requested changes

2020-10-13 14:03 UTC, alesanchezr commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
>  + ***Resolver*** se utiliza para cambiar el estado de una promesa de pendiente a cumplida.
we should keep the function name in english: `resolve` and `reject` because it is a reserved word.

2020-10-13 14:03 UTC, alesanchezr commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +[Ojo]]
This is also a reserved word `[[warning]]`

2020-11-03 11:15 UTC, marcogonzalo requested changes

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +3	correSegundo();
```suggestion
3	ejecutarSegundo();
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +6    function correSegundo(){
```suggestion
6    function ejecutarSegundo(){
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +9   correPrimero();
```suggestion
9   ejecutarPrimero();
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +RESULTADO CONSOLA:
```suggestion
RESULTADO EN CONSOLA:
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +  > También quiero correr cuando se ejecuta correPrimero //Esta línea de código tuvo que esperar a que correSegundo() terminara.
```suggestion
  > También quiero correr cuando se ejecuta ejecutarPrimero //Esta línea de código tuvo que esperar a que ejecutarSegundo() terminara.
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> ++ ```correPrimero()``` se añade al call stack porque la llamamos (línea 9).
```suggestion
+ ```ejecutarPrimero()``` se añade al call stack porque la llamamos (línea 9).
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> ++ Vemos nuestro primer ```console.log``` (línea 2), después de eso, se llama a ```correSegundo ()``` (línea 3).
```suggestion
+ Vemos nuestro primer ```console.log``` (línea 2), después de eso, se llama a ```ejecutarSegundo ()``` (línea 3).
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> ++ ```correPrimero ()``` hace una pausa en su ejecución y ```correSegundo ()``` comienza a ejecutarse.
```suggestion
+ ```ejecutarPrimero ()``` hace una pausa en su ejecución y ```ejecutarSegundo ()``` comienza a ejecutarse.
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> ++ Una vez que ```correSegundo ()``` termina, ```correPrimero ()``` comienza nuevamente, ejecutando el resto de su código, el último ```console.log``` (línea 4).
```suggestion
+ Una vez que ```ejecutarSegundo()``` termina, ```ejecutarPrimero()``` comienza nuevamente, ejecutando el resto de su código, el último ```console.log``` (línea 4).
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +1    function correPrimero(unaFuncion){
```suggestion
1    function ejecutarPrimero(unaFuncion){
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +4	correSegundo();
```suggestion
4	ejecutarSegundo();
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +5	console.log("También quiero correr cuando se ejecute correPrimero");
```suggestion
5	console.log("También quiero correr cuando se ejecute ejecutarPrimero");
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +7    function correSegundo(){
```suggestion
7    function ejecutarSegundo(){
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +10   correPrimero(unaTercera);
```suggestion
10   ejecutarPrimero(unaTercera);
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +RESULTADO CONSOLA:
```suggestion
RESULTADO EN CONSOLA:
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +  > También quiero correr cuando se ejecuta correPrimero
```suggestion
  > También quiero correr cuando se ejecuta ejecutarPrimero
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +Hemos agregado una nueva función ```unaTercera ()``` (línea 12), que muestra los registros de la consola: "esto es una locura"; pero no la estamos llamando directamente, en cambio, estamos pasando el
```suggestion
Hemos agregado una nueva función ```unaTercera ()``` (línea 12), que muestra los registros de la consola: "esto es una locura"; pero no la estamos llamando directamente, en cambio, estamos pasando el nombre como parámetro a ```ejecutarPrimero()``` (línea 10).
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +```correPrimero(unaFunción)``` ahora espera un valor (línea 1) que llamaremos como si fuera una función (línea 3).
```suggestion
```ejecutarPrimero(unaFunción)``` ahora espera un valor (línea 1) que llamaremos como si fuera una función (línea 3).
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +Esto produce una nueva impresión en la consola: "esto es una locura", antes de llamar a ```correSegundo ()``` (línea 4).
```suggestion
Esto produce una nueva impresión en la consola: "esto es una locura", antes de llamar a ```ejecutarSegundo()``` (línea 4). 
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +/*RESULTADO CONSOLA
```suggestion
/*RESULTADO EN CONSOLA
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
>  En un sitio web de la vida real, los usuarios tendrán que esperar mucho tiempo para ver algo, todo porque el procesamiento ***DOM*** tiene que esperar a que lleguen las imágenes desde el servidor; y
```suggestion
En un sitio web de la vida real, una persona tendrá que esperar mucho tiempo para ver algo, todo porque el procesamiento ***DOM*** tiene que esperar a que lleguen las imágenes desde el servidor; y esto es todo porque estamos usando el mismo hilo de ejecución para todo.
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +/*RESULTADO CONSOLA:
```suggestion
/*RESULTADO EN CONSOLA:
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +Javascript ofrece varias funciones asíncronas predefinidas que podemos utilizar para resolver cualquier escenario posible. Algunos de ellas son:
```suggestion
JavaScript ofrece varias funciones asíncronas predefinidas que podemos utilizar para resolver cualquier escenario posible. Algunas de ellas son:
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +Tenga en cuenta que cualquier llamada a la red puede fallar por diversas razones, siempre debemos estar preparados para la falla.
```suggestion
Debemos tener en cuenta que cualquier llamada a la red puede fallar por diversas razones, Siempre debemos estar preparados para la falla.
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +/*RESULTADO CONSOLADO:
```suggestion
/*RESULTADO EN CONSOLA:
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +	/*RESULTADO CONSOLA:
```suggestion
	/*RESULTADO EN CONSOLA:
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +| Recuerda que las expresiones await sólo son válidas dentro de funciones asíncronas. Si los usa fuera, tendrá un error de sintaxis.
```suggestion
| Recuerda que las expresiones await sólo son válidas dentro de funciones asíncronas. Si las usas fuera, tendrás un error de sintaxis.
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +/*RRESULTADO CONSOLA:
```suggestion
/*RESULTADO EN CONSOLA:
```

2020-11-03 11:15 UTC, marcogonzalo commented on src/content/lesson/asynchronous-algorithms-async-await.es.md
> +/*RESULTADO CONSOLA:
```suggestion
/*RESULTADO EN CONSOLA:
```

2020-11-05 03:15 UTC, alesanchezr approved these changes

2020-11-05 03:19 UTC, merged