class component section missing
breatheco-de/content pull request #228
Opened 2020-10-13 17:57 UTC by ElviraQDP

content needs to be revised to make a new version

2020-10-20 13:47 UTC, alesanchezr requested changes

2020-10-20 13:47 UTC, alesanchezr commented on src/content/lesson/making-react-components.es.md
> +//o como un componente de clae
clae => clase

2020-11-03 11:20 UTC, marcogonzalo requested changes

2020-11-03 11:20 UTC, marcogonzalo commented on src/content/lesson/making-react-components.es.md
>  ## En React.js todo es un `<Component />`
```suggestion
## En React.js todo es un `<Componente />`
```

2020-11-03 11:20 UTC, marcogonzalo commented on src/content/lesson/making-react-components.es.md
> +React.js separa tu código en pequeñas partes llamadas Componentes que pueden crearse / definirse como **class** o como **function**.  Cada componente es como una aplicación de React más pequeña que t
```suggestion
React.js separa tu código en pequeñas partes llamadas Componentes que pueden crearse / definirse como **class** o como **function**.  Cada componente es como una aplicación de React más pequeña que tiene su propia lógica y tiene un propósito final que es renderizar algo. Por ejemplo: un `navbar` de bootstrap, una _dropdown list_ (lista desplegable), un modelo, un formulario dinámico, galería de imágenes, formulario de suscripción, casi todo puede diseñarse y codificarse como un componente React). Para hacer eso, el componente de React debe tener un `return` que devuelva código JSX (HTML + JS anidado).
```

2020-11-03 11:20 UTC, marcogonzalo commented on src/content/lesson/making-react-components.es.md
> +Y, por último, deberías indicarle a React dónde debe renderizar ese componente en el DOM.
```suggestion
Y, por último, debemos indicarle a React dónde debe renderizar ese componente en el DOM.
```

2020-11-03 11:20 UTC, marcogonzalo commented on src/content/lesson/making-react-components.es.md
> +Y, por último, deberías indicarle a React dónde debe renderizar ese componente en el DOM.
Venimos hablando en segunda persona plural

2020-11-05 03:10 UTC, alesanchezr approved these changes

2020-11-05 03:12 UTC, merged