consistency, translation missing, typos fixed
breatheco-de/content pull request #230
Opened 2020-10-14 16:22 UTC by ElviraQDP

2020-10-18 12:24 UTC, marcogonzalo requested changes
@ElviraQDP dejo algunas observaciones y sugerencias de corrección:
- [x] **Línea 3, corrección**: requiere una mayúscula después del punto: "de evitar. En esta lección".
- [x] **Línea 14, corrección**: colocar una coma antes del pero en "de poco código, pero intentar".
- [x] **Línea 14, corrección**: colocar una coma en "Por otro lado, los componentes de clase".
- [x] **Línea 14, sugerencia**: colocar una coma en "son confusos, tanto para los humanos como para".
- [x] **Línea 14, sugerencia**: incorporar una "y" en "como para las máquinas, y no suelen entregar una experiencia positiva al desarrollador".
- [x] **Línea 18, corrección**: falta una tilde en "para saber cuándo usar hooks".
- [x] **Línea 22, sugerencia**: según la RAE el "solo", en cualquier circunstancia, ya no debe llevar tilde, ya que el contexto bien proveído permite diferenciar el del solamente del de soledad.
- [x] **Línea 24, sugerencia**: reemplazar coma por punto en "comprenderás mejor cuándo usar Hooks. Si no crees que los necesitas, ¡NO los uses!".
- [x] **Línea 42, corrección**: falta un signo de exclamación en "¡casi inevitable!"
- [x] **Línea 49, sugerencia**: falta una coma después de "Básicamente"
- [x] **Línea 61, corrección**: falta una tilde en "Tú".
- [x] **Línea 61, corrección**: hay dos palabras pegadas en "guardamos en".
- [x] **Línea 66, corrección**: faltan tildes en "aquí está el código" (aquí, está".
- [x] **Línea 70, sugerencia**: Si retiramos el "nosotros" no hacemos referencia a un género específico, por lo que el contenido no da sensación de ir dirigido más a un público (másculino, por la pluralización sugerida por la RAE). El contenido mantiene su sentido sin esa palabra.
- [ ] **Línea 72, sugerencia**: La misma que en el caso anterior.
- [x] **Línea 78, sugerencia**: retiraría el ", por ejemplo" y colocaría mayúscula en "React"
- [ ] **Línea 120, corrección**: Cerrar el signo de exclamación.
- [ ] **Línea 123, observación**: el "Todos" no se entiende del todo como la referencia a un "to-do list", ¿habrá otra forma de colocarlo? ¿"Lista de tareas"? ¿"Lista de pendientes"? ¿"Lista de to-dos"?
- [ ] **Línea 136, observación**: cambia la forma de dirigirse a la persona. Dice "Inicialice" en lugar de "Inicializa"
- [ ] **Línea 151, corrección**: debería ser "la demo" siendo una abreviación o expresión acortada de "la demostración". Para que sea masculino, sería "el video de demo".

2020-10-20 14:36 UTC, ElviraQDP commented
@marcogonzalo comentarios añadidos

2020-11-03 11:33 UTC, marcogonzalo requested changes

2020-11-03 11:33 UTC, marcogonzalo commented on src/content/lesson/react-hooks-explained.es.md
> +Los componentes funcionales que pasan props son sorprendentes porque son simples, tienen un rendimiento rápido y requieren de poco código, ero intentar mantener todos los componentes encapsulados pue
```suggestion
Los componentes funcionales que pasan props son sorprendentes porque son simples, tienen un rendimiento rápido y requieren de poco código, pero intentar mantener todos los componentes encapsulados puede volverse un infierno. Por otro lado, los componentes de clase a menudo son confusos, tanto para los humanos como para la máquinas, y no suelen entregar una experiencia positiva al desarrollador. Los Hooks proveen una forma para usar los métodos del state y del ciclo de vida con muy poco código, entregándole super poderes a tus componentes:
```

2020-11-03 11:33 UTC, marcogonzalo commented on src/content/lesson/react-hooks-explained.es.md
> +subtitle: "Los Hooks son la nueva forma de crear componentes React, son imposibles de evitar. En esta lección no enfocaremos en los 2 más importantes: useState y useEffect"
```suggestion
subtitle: "Los Hooks son la nueva forma de crear componentes React, son imposibles de evitar. En esta lección nos enfocaremos en los 2 más importantes: useState y useEffect"
```

2020-11-03 11:33 UTC, marcogonzalo commented on src/content/lesson/react-hooks-explained.es.md
> +2. Si quieres obtener algunos datos sólo al comienzo de la ejecución del programa, usa el hook **useEffect**.
```suggestion
2. Si quieres obtener algunos datos solo al comienzo de la ejecución del programa, usa el hook **useEffect**.
```

2020-11-03 11:33 UTC, marcogonzalo commented on src/content/lesson/react-hooks-explained.es.md
> +A medida que tengas más experiencia, comprenderás mejor cuándo usar Hooks. Si no los necesitas, ¡NO lo uses! ¡Cuanto menos mejor!
```suggestion
A medida que tengas más experiencia, comprenderás mejor cuándo usar Hooks. Si no los necesitas, ¡NO los uses! ¡Cuanto menos mejor!
```

2020-11-03 11:33 UTC, marcogonzalo commented on src/content/lesson/react-hooks-explained.es.md
> +Para implementar un "Ventana Modal" decidimos crear una variable hook llamada `opened` que es `true` si la ventana modal debe mostrarse al usuario.
```suggestion
Para implementar un "Ventana Modal", hemos decidido crear una variable hook llamada `opened` que es `true` si la ventana modal debe mostrarse en pantalla.
```

2020-11-03 11:33 UTC, marcogonzalo commented on src/content/lesson/react-hooks-explained.es.md
> +Si el usuario hace clic en "close" simplemente usamos la función hook `setOpened` para cambiar el valor de `opened` a `false`.
```suggestion
Si una persona hace clic en "close", simplemente usamos la función hook `setOpened` para cambiar el valor de `opened` a `false`.
```

2020-11-03 11:33 UTC, marcogonzalo commented on src/content/lesson/react-hooks-explained.es.md
> +El UseEffect es otro hook increíble que probablemente tendrás que usar en casi todas las aplicaciones de React cuando el componente se renderice,.
```suggestion
El UseEffect es otro hook increíble que probablemente tendrás que usar en casi todas las aplicaciones de React cuando el componente se renderice.
```

2020-11-03 11:33 UTC, marcogonzalo commented on src/content/lesson/react-hooks-explained.es.md
> +Por ejemplo, digamos que estoy construyendo una lista de tareas y tengo que cargar la lista de tareas desde una API. Tendré que buscar(fetch) la información justo después de que el componente se rend
```suggestion
Por ejemplo, digamos que estamos construyendo una lista de tareas y tenemos que cargar la lista de tareas desde una API. Tendremos que buscar (fetch) la información, justo después de que el componente se renderice por primera vez:
```

2020-12-10 18:13 UTC, alesanchezr approved these changes

2020-12-10 18:32 UTC, marcogonzalo approved these changes

2021-01-24 18:32 UTC, alesanchezr approved these changes

2021-01-24 18:32 UTC, merged