translation added
breatheco-de/content pull request #258
Opened 2020-10-22 17:55 UTC by ElviraQDP

2020-11-12 18:56 UTC, marcogonzalo requested changes

2020-11-12 18:56 UTC, marcogonzalo commented on rounded-image-using-div-instead-of-img-tag.es.md
> +La manera obvia de crear una imagen de perfil redonda es crear una etiqueta de imagen y aplicarle  `border-radius:100%`. El problema esta solución, es que sólo funciona en imágenes cuadradas...las im
```suggestion
La manera obvia de crear una imagen de perfil redonda es crear una etiqueta de imagen y aplicarle  `border-radius:100%`. El problema de esta solución, es que sólo funciona en imágenes cuadradas (igual ancho y alto)... las imágenes de perfil con diferentes alturas y ancho no se verán como círculos sino como óvalos:
```

2020-11-12 18:56 UTC, marcogonzalo commented on rounded-image-using-div-instead-of-img-tag.es.md
> +Si la imagen es más grande que el div (o de diferentes proorciones) podemos ajustar la background-position o el background-size para escogerque parte de la imagen queremos que se vea dentro del círcu
```suggestion
Si la imagen es más grande que el div (o de diferentes proporciones), podemos ajustar la background-position o el background-size, para escoger qué parte de la imagen queremos que se vea dentro del círculo.
```

2020-11-12 18:56 UTC, marcogonzalo commented on rounded-image-using-div-instead-of-img-tag.es.md
> +![]Usando una imagen de fondo/background image en vez de una etiqueta de imagen para la adaptabilidad](../../assets/images/1251c891-ac88-464f-ae58-5c9d7abe081cScreenShot20190524at121150PM.png)
```suggestion
![Usando una imagen de fondo (background-image) en vez de una etiqueta de imagen para la adaptabilidad](../../assets/images/1251c891-ac88-464f-ae58-5c9d7abe081cScreenShot20190524at121150PM.png)
```

2020-12-01 03:30 UTC, alesanchezr approved these changes

2020-12-01 03:45 UTC, alesanchezr approved these changes

2020-12-01 03:45 UTC, merged