consistency check
breatheco-de/content pull request #267
Opened 2020-10-23 20:59 UTC by ElviraQDP

2020-10-26 18:04 UTC, alesanchezr approved these changes

2020-11-12 19:14 UTC, marcogonzalo requested changes

2020-11-12 19:14 UTC, marcogonzalo commented on src/content/lesson/backend-developer.es.md
> +No hace mucho tiempo, los navegadores eran muy tontos. Todo lo que hacían era renderizar documentos HTML en una versión muy básica de HTML. No había CSS, ni JS ¡Eso significa que los desarrolladores
```suggestion
No hace mucho tiempo, los navegadores eran muy tontos. Todo lo que hacían era renderizar documentos HTML en una versión muy básica de HTML. No había CSS, ni JS. ¡Eso significa que los desarrolladores web front-end no existían!
```

2020-11-12 19:14 UTC, marcogonzalo commented on src/content/lesson/backend-developer.es.md
> ++ Conectartte a una o varias bases de datos al mismo tiempo y recuperar / procesar los datos.
```suggestion
+ Conectarte a una o varias bases de datos al mismo tiempo y recuperar / procesar los datos.
```

2020-11-12 19:14 UTC, marcogonzalo commented on src/content/lesson/backend-developer.es.md
> ++ Abrir / crear / eliminar archivos locales de la máquina y actualizalos con contenido nuevo.
```suggestion
+ Abrir / crear / eliminar archivos locales de la máquina y actualizarlos con contenido nuevo.
```

2020-11-12 19:14 UTC, marcogonzalo commented on src/content/lesson/backend-developer.es.md
> ++ **Desarrollar y ejecutar la parte lógica de las necesidades del negocio:** Conectarte con aplicaciones de terceros, hardware externos y cualquier otra necesidad cdel negocio.
```suggestion
+ **Desarrollar y ejecutar la parte lógica del negocio:** Conectarte con aplicaciones de terceros, hardware externos y cualquier otra necesidad del negocio.
```

2020-11-13 19:18 UTC, alesanchezr approved these changes

2020-11-13 19:18 UTC, merged