draft of CFN lesson without images
breatheco-de/content pull request #340
Opened 2020-11-12 18:47 UTC by ElviraQDP

missing images

2020-11-12 22:00 UTC, marcogonzalo requested changes

2020-11-12 22:00 UTC, marcogonzalo commented on src/content/lesson/[draft]crow-foot-notation.md
> ++ zero or one:
```suggestion
+ zero or one
```

2020-11-12 22:00 UTC, marcogonzalo commented on src/content/lesson/[draft]crow-foot-notation.md
> ++ zero or many:
```suggestion
+ zero or many
```

2020-12-22 18:11 UTC, alesanchezr commented
Change wording to avoid copy-cat
First paragraph its duplciated.

2021-01-16 17:45 UTC, JimenaEB requested changes

2021-02-09 15:41 UTC, ElviraQDP reviewed
Que falta corregir @marcogonzalo ?

2021-05-06 21:01 UTC, closed without merging