lesson fixed (examples)
breatheco-de/content pull request #358
Opened 2020-12-15 20:30 UTC by ElviraQDP

lesson's examples fixed

2020-12-16 17:51 UTC, marcogonzalo requested changes
@alesanchezr te he dejado una mención en la revisión para que verifiques algo

2020-12-16 17:51 UTC, marcogonzalo commented on src/content/lesson/everything-you-need-to-start-using-sqlalchemy.md
> +INSERT INTO class PIZZA(4, 'meat');
¿"INSERT INTO class"?  Nunca he visto esas consultas con 'class ALGO'. @alesanchezr porfa verifica esto, por si desconozco algo sobre el SQL "genérico"

2020-12-16 17:51 UTC, marcogonzalo commented on src/content/lesson/everything-you-need-to-start-using-sqlalchemy.md
> +```jsx
¿Hay un formateador para SQL? Vendría mejor ;-)

2020-12-16 17:51 UTC, marcogonzalo commented on src/content/lesson/making-react-components.md
> +        foo: "var"
falta un espaciado para que tenga la sangría correcta dentro de la llave

2020-12-16 17:51 UTC, marcogonzalo commented on src/content/lesson/making-react-components.md
> +        }
Ojo con la sangría aquí.

2020-12-17 15:23 UTC, ElviraQDP commented on src/content/lesson/everything-you-need-to-start-using-sqlalchemy.md
> +```jsx
pregunte a @alesanchezr y no dijo nada en particular

2020-12-22 18:15 UTC, alesanchezr commented
Rewrite SQLAlchmy transactions to be more human, less academic.

2021-01-14 22:18 UTC, alesanchezr approved these changes

2021-01-21 22:57 UTC, alesanchezr approved these changes

2021-01-24 18:31 UTC, alesanchezr approved these changes

2021-01-24 18:31 UTC, merged