feat: add lesson typeScript
breatheco-de/content pull request #464
Opened 2021-04-18 01:08 UTC by mortegac

add Expressjs new lessons

2021-04-21 15:33 UTC, alesanchezr commented on src/content/lesson/building-apis-with-nodejs-expressjs.es.md
> +Si no sabes qué es una API REST, recomiendo [leer sobre esto aquí](http://content.breatheco.de/lesson/understanding-rest-apis).
esta ruta debe ser relativa usa `/lesson/understanding-rest-apis` en vez de `http://content.breatheco.de/lesson/understanding-rest-apis`

2021-04-21 16:02 UTC, alesanchezr requested changes
Algunos cambios menores

2021-04-21 16:02 UTC, alesanchezr commented on src/content/lesson/what-is-typescript.es.md
> +***
Los `***` no son necesarios, ya breathecode les agega un subrayado a los titurlos.

2021-04-21 16:02 UTC, alesanchezr commented on src/content/lesson/what-is-typescript.es.md
> +```
tienes que agregarle el lenguage al bloque de codigo

2021-04-21 16:02 UTC, alesanchezr commented on src/content/lesson/what-is-typescript.es.md
> +***
Remover el `***`

2021-04-21 16:12 UTC, ElviraQDP reviewed
building apis with nodejs express.es.md:

linea 34 : falta articulo "la" antes de libreria
linea 40: crear o podemos?, corregir computar por computador
agregar un espacio entre la linea 79 y 80
linea 82: Ejecuta cambiar por "ejecute"
linea 131: suprimir un salto de linea
144: la Y debe ir en minúscula
linea 175: Midleware se escribe "Middleware"
linea 177:middleware corregir x 3
179: idem
186: middleware

what is typescript:
linea 11: " dependiendo del valor que se "le" asigne. espacio extra despues de "Podemos". palabra los repetida.
linea 13: no suena mejor "sin ningún tipo de conversión"
linea 28:  agrega, cambiar el agregar. espacio extra despues del punto seguido.
linea 31: no suena mejor "implementando características en un lenguaje"
linea 41: "los valores deben tener el mismo tipo de dato que la variable"
linea 95: falta punto final
linea 101: falta punto final.
linea 108: falta punto final
linea 121: si su implementación? no entiendo
linea 123: un conjjunto de reglas creadas por ti. Esto puede ayudarte a....
linea 136: al reves, la interface `Lakes`. Revisar sentido de la frase completa
linea 148: Como puedes ver, no importa el orden en el que asignes, Sin embargo no puedes.....
linea 149: Deberás
línea 154: falta un salto de línea
linea 157: cambiar el parrafo de usted a tu.
línea 178: Cambiar conclusión de usted a tu

2021-04-21 16:13 UTC, ElviraQDP commented on src/content/lesson/building-apis-with-nodejs-expressjs.es.md
> +Una vez finalizada la instalación podemos crearas un archivo server.js ya agregaremos las siguientes líneas, el computar comenzará a escuchar las solicitudes HTTP:
computador le decimos

2021-04-27 14:49 UTC, mortegac commented on src/content/lesson/building-apis-with-nodejs-expressjs.es.md
> +Una vez finalizada la instalación podemos crearas un archivo server.js ya agregaremos las siguientes líneas, el computar comenzará a escuchar las solicitudes HTTP:
Listo

2021-04-27 14:50 UTC, mortegac commented on src/content/lesson/building-apis-with-nodejs-expressjs.es.md
> +const express = require('express'); #aquí importamos la librería Expressjs en nuestro archivo.
listo

2021-04-27 14:53 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +```
listo, los de typescript los deje con `javascript`

2021-04-27 14:53 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +```
listo

2021-04-27 14:54 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +***
Los uso para dejar una linea que separe el contenido.  Pero las sacos

2021-04-27 14:54 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +***
listo

2021-04-27 14:55 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +***
listo

2021-04-27 14:55 UTC, mortegac commented on src/content/lesson/building-apis-with-nodejs-expressjs.es.md
> +| :point_up: Puede leer más sobre las API REST en [esta lección de BreatheCode](http://content.breatheco.de/lesson/understanding-rest-apis).<br /> Aquí hay un video de 8 minutos que explica REST: htt
listo

2021-04-27 14:55 UTC, mortegac commented on src/content/lesson/building-apis-with-nodejs-expressjs.es.md
> +Si no sabes qué es una API REST, recomiendo [leer sobre esto aquí](http://content.breatheco.de/lesson/understanding-rest-apis).
listo

2021-04-27 14:56 UTC, mortegac commented on src/content/lesson/building-apis-with-nodejs-expressjs.es.md
> +Una vez finalizada la instalación podemos crearas un archivo server.js ya agregaremos las siguientes líneas, el computar comenzará a escuchar las solicitudes HTTP:
listo deje el computador

2021-04-27 17:24 UTC, mortegac commented
@alesanchezr @ElviraQDP  solucione todas las observaciones para que revisen el PR

2021-05-06 20:49 UTC, ElviraQDP requested changes

2021-05-06 20:49 UTC, ElviraQDP commented on src/content/lesson/what-is-typescript.es.md
> +- **Boolean**:  Solo acepta valores: Verdadero 0 Falso
Ese es un cero o una o?

2021-05-06 20:49 UTC, ElviraQDP commented on src/content/lesson/what-is-typescript.es.md
> +- **Void**: Se utiliza para indicar que no tenemos u tipo de datos definido
no tenemos "un"

2021-05-06 20:49 UTC, ElviraQDP commented on src/content/lesson/what-is-typescript.es.md
> +Al igual que los tipos de variables simples, estos objetos también deberán seguir un conjunto de reglas creadas por ti. Esto puede ayudarlo a escribir código con más confianza y con menos posibilidad
"esto puede ayudarte", cambiar usted por tu

2021-05-06 20:49 UTC, ElviraQDP commented on src/content/lesson/what-is-typescript.es.md
> +Como puede ver, no importa el orden en el que asignes. Sin embargo, no puede omitir un valor.
Como puedes ver, no importa el orden que le asignes. Sin embargo no puedes omitir un valor

2021-05-06 20:49 UTC, ElviraQDP commented on src/content/lesson/what-is-typescript.es.md
> +Deberá asignar un valor a cada propiedad para evitar errores al compilar el código.
Deberás

2021-05-06 20:49 UTC, ElviraQDP commented on src/content/lesson/what-is-typescript.es.md
> +A veces, es posible que necesite una propiedad solo para algunos objetos específicos.
necesites

2021-05-06 20:49 UTC, ElviraQDP commented on src/content/lesson/what-is-typescript.es.md
> +Por ejemplo, supongamos que desea agregar una propiedad para especificar los meses en los que se congela un lago. Si agrega la propiedad directamente a la interfaz, como hemos hecho hasta ahora, obte
deseas. cambiar todos los usted por tu

2021-05-06 20:49 UTC, ElviraQDP commented on src/content/lesson/what-is-typescript.es.md
> +En tales casos, puede agregar un signo de interrogación `?` después del nombre de una propiedad para establecerla como opcional en la declaración de la interfaz. De esta manera, no obtendrá un error
usted por tu

2021-05-16 18:50 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +- **Boolean**:  Solo acepta valores: Verdadero 0 Falso
una "o"

2021-05-16 18:51 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +- **Boolean**:  Solo acepta valores: Verdadero 0 Falso
corregido

2021-05-16 18:51 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +- **Void**: Se utiliza para indicar que no tenemos u tipo de datos definido
corregido

2021-05-16 18:52 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +Al igual que los tipos de variables simples, estos objetos también deberán seguir un conjunto de reglas creadas por ti. Esto puede ayudarlo a escribir código con más confianza y con menos posibilidad
listo

2021-05-16 18:52 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +Como puede ver, no importa el orden en el que asignes. Sin embargo, no puede omitir un valor.
corregido

2021-05-16 18:53 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +Deberá asignar un valor a cada propiedad para evitar errores al compilar el código.
corregido

2021-05-16 18:53 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +A veces, es posible que necesite una propiedad solo para algunos objetos específicos.
corregido

2021-05-16 18:53 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +Por ejemplo, supongamos que desea agregar una propiedad para especificar los meses en los que se congela un lago. Si agrega la propiedad directamente a la interfaz, como hemos hecho hasta ahora, obte
corregido

2021-05-16 18:54 UTC, mortegac commented on src/content/lesson/what-is-typescript.es.md
> +En tales casos, puede agregar un signo de interrogación `?` después del nombre de una propiedad para establecerla como opcional en la declaración de la interfaz. De esta manera, no obtendrá un error
listo

2021-05-18 15:04 UTC, merged