Update how-to-create-unit-testing-with-Javascript-and-Jest.es.md
breatheco-de/content pull request #470
Opened 2021-05-01 16:39 UTC by jatv93

Minor changes in the text

2021-05-01 18:48 UTC, ElviraQDP requested changes

2021-05-01 18:48 UTC, ElviraQDP commented on src/content/lesson/how-to-create-unit-testing-with-Javascript-and-Jest.es.md
> ++ **Las pruebas unitarias mejoran el trabajo en equipo**. Podrán seguir la lógica detrás de tu código y tu equipo será capaz de coordinar su código en consecuencia. Al revisar los códigos de los demá
Aqui es "podrás" en vez de podrán

2021-05-06 22:25 UTC, ElviraQDP approved these changes

2021-05-06 22:26 UTC, ElviraQDP approved these changes

2021-05-19 18:55 UTC, Jtoledo88 approved these changes

2021-05-19 18:57 UTC, merged