Misspell Challenge
breatheco-de/content pull request #600
Opened 2021-11-15 23:48 UTC by keenerz

Corrected "recommend"

2021-11-18 10:41 UTC, ElviraQDP approved these changes

2021-11-18 11:23 UTC, jatv93 requested changes
The spelling is not right, the correct spelling is recommend

2021-12-15 10:37 UTC, jatv93 requested changes
The right spelling is recommend

2021-12-15 16:58 UTC, ElviraQDP approved these changes

2021-12-15 17:05 UTC, ElviraQDP approved these changes

2021-12-15 17:06 UTC, jatv93 approved these changes

2021-12-18 15:46 UTC, merged