missing property in spanish README
breatheco-de/content pull request #665
Opened 2022-01-14 18:00 UTC by ElviraQDP

2022-01-19 15:21 UTC, Jtoledo88 submitted a review, later dismissed
Aprobacion de cambios

2022-01-19 15:26 UTC, jatv93 requested changes
Hay algunos errores ortográficos

2022-01-20 20:55 UTC, ElviraQDP reviewed
mispells corrected

2022-01-22 14:55 UTC, jatv93 approved these changes

2022-02-05 06:54 UTC, alesanchezr approved these changes

2022-02-05 06:54 UTC, merged